
try:
    let_us_cause_a_NameError
except NameError as err:
    print (err, '--> our error message')